### ISSUE TITLE
Tenant Manager Chart missing

### ISSUE THREAD

**Issue by agilgur5** [aquasecurity/aqua-helm#117]
I would like to use the Tenant Manager and I use Helm, but there is no Tenant Manager Chart.

I added it myself in my PR #99 instead of waiting for someone from Aqua to do so, but for some reason that was closed with a one-liner saying "we currently don't need the tenant manager to be in the helm charts", despite me needing it... I said as much in https://github.com/aquasecurity/aqua-helm/pull/99#issuecomment-665088383 as well

It seems like this repository has a history of rejecting useful PRs with little to no comments, like all the ones mentioned in #92 and #102, among others... This does not give a good experience to customers 😕 , especially ones that are doing work to improve Aqua's products.

**Comment by rshmiel** [comment]
@agilgur5 TM was added to 5.3 and 6.0 branches.
see 6.0: https://github.com/aquasecurity/aqua-helm/tree/6.0/tenant-manager
thanks for reporting
