### ISSUE TITLE
No changelogs??

### ISSUE THREAD

**Issue by agilgur5** [aquasecurity/aqua-helm#123]
None of the Charts seem to have changelogs, making it very difficult to upgrade or rely on this repo, as one has to read through each commit to understand the changes made. To make matters worse, most of the commits and PRs in this repo also have little to no details in their titles and messages, so the commit log is not really useful as a changelog either.

Per #82 , this repository and the corresponding Helm registry also overwrite existing versions and make breaking changes without bumping version at all, making even pinning to exact version unreliable. Overwriting existing versions is generally poor practice outside of security incidents where the better response is usually to unpublish. Breaking changes like those mentioned in #82 or in https://github.com/aquasecurity/aqua-helm/commit/70ae91735fff3db823569c6a5bab689267e3ba9a seem to be made with some frequency too. That would make a changelog, if not full upgrade docs, even more important.

If SemVer is not being followed, this should be very explicitly written in multiple places in the docs, and the alternate versioning strategy explicitly written as well. Right now it is misleadingly SemVer, whereas CalVer may perhaps be more fitting given current usage.

Having a changelog will also make it easier to follow SemVer as one has to delineate breaking changes, new features, and patches from each other.

**Comment by KoppulaRajender** [comment]
Hi @agilgur5, Started changelog from #239 and will maintain the changelog and chartversions going forward as well.
