### ISSUE TITLE
Update /aqua-quickstart/Chart.yaml#L1 from `apiVersion: v2` to `apiVersion: v1`

### ISSUE THREAD

**Issue by sanjay-shah** [aquasecurity/aqua-helm#146]
Update https://github.com/aquasecurity/aqua-helm/blob/cc7851c24e6b95dc6ac9bb364fa13cb895e09c01/aqua-quickstart/Chart.yaml#L1 from `apiVersion: v2` to `apiVersion: v1`. v2 is still not supported in several implementation.

**Comment by KoppulaRajender** [comment]
@sanjay-shah - the current charts working fine with v2. Can you explain what are the issues you come across with v2 version compared to v1 so we can try it out and fix them.

**Comment by KoppulaRajender** [comment]
Please re-open this ticket for any related issues.
