### ISSUE TITLE
 Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend): missing required field "servicePort" in io.k8s.api.extensions.v1beta1.IngressBackend

### ISSUE THREAD

**Issue by FeedTheDarkside** [aquasecurity/aqua-helm#148]
In the helm template for web_ingress.yaml, there is a variable defined for externalPort.  There is no such value to define in the values.yaml.  There is also no definition for this in values definition in the README.md.  As a result of this, the error in the subject header is generated.

**Comment by kenmccann** [comment]
@rshmiel @xB-2048 Please validate.  Easily reproducible just by setting ingress create = true.  web-ingress.yaml references externalPort which does not exist in values.yaml

**Comment by rshmiel** [comment]
fixed. @kenmccann  thanks!
