### ISSUE TITLE
Error: execution error at (aqua-enforcer/charts/enforcer/templates/enforcer-token-secret.yaml:14:13): A valid .Values.enforcerToken entry required! 

### ISSUE THREAD

**Issue by mikeykubes** [aquasecurity/aqua-helm#149]
I am getting an error when trying to use Helm with ArgoCD.  My values.yaml file does include the enforcerToken value.

enforcerToken: "xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx"

I scrubbed the value but that is what is listed in my values.yaml file.  When I look at my parameters section in Argo it shows the proper parameters are being populated when I try to patch the file to swap the token.  I am not sure if there is a bug in the yaml file listed in the subject or if I am using it incorrectly.  

Thanks.

**Comment by rshmiel** [comment]
Working with the support team on this issue

**Comment by KoppulaRajender** [comment]
From support ticket found this issue is within argoCD config and not with the helm charts.
Closing Ticket.
