### ISSUE TITLE
enforcer helm chart doesn't support setting up multiple gateways

### ISSUE THREAD

**Issue by coolhitaga** [aquasecurity/aqua-helm#150]
The current helm chart doesn't support passing values of multiple gateways/envoys. Raising this issue to resolve it.

https://github.com/aquasecurity/aqua-helm/blob/master/enforcer/templates/enforcer-daemonset.yaml#L53

Update the  enforcer-daemonset.yaml:
  value: {{ .Values.gate.host | default "aqua-gateway-svc:8443" }}

And then pass a comma separated list of host:port similar to the following in values.yaml:
 
gate:
  host: 20.73.195.115:8443,20.73.33.34:8443

**Comment by ericgomes56** [comment]
The Enforcers are able to pass in multiple GW values by the 'AQUA_SERVER' environment variable (e.g., AQUA_SERVER=aqua-gateway:8443, aqua-gateway-svc:8443, and so on).  As you pointed out, the parsing is done incorrectly in the enforcer/values.yaml on line 53.

**Comment by ericgomes56** [comment]
The Enforcers are able to pass in multiple GW values by the 'AQUA_SERVER' environment variable (e.g., AQUA_SERVER=aqua-gateway:8443, aqua-gateway-svc:8443, and so on). As you pointed out, the parsing is done incorrectly in the enforcer/templates/enforcer-daemonset.yaml on line 53.

**Comment by ericgomes56** [comment]
@coolhitaga thanks for pointing this out. The Enforcers are in fact able to pass in multiple GW values by the 'AQUA_SERVER' environment variable (e.g., AQUA_SERVER=aqua-gateway:8443, aqua-gateway-svc:8443, and so on). As you pointed out, the parsing is done incorrectly in the enforcer/templates/enforcer-daemonset.yaml on line 53.

**Comment by ericgomes56** [comment]
@coolhitaga thanks for raising the awareness on this problem.  The Enforcers are in fact able to pass in multiple GW values by the 'AQUA_SERVER' environment variable (e.g., AQUA_SERVER=aqua-gateway:8443, aqua-gateway-svc:8443, and so on). As you pointed out, the parsing is done incorrectly in the enforcer/templates/enforcer-daemonset.yaml on line 53.

**Comment by coolhitaga** [comment]
Aqua team, is there an update on this issue. By when do you think we can have a fix of it?

**Comment by ericgomes56** [comment]
@coolhitaga I believe @rshmiel is working on this issue.  Feel free to submit a PR so we can resolve the issue quicker.

**Comment by rshmiel** [comment]
We do work on a fix and it will be ready soon
Will update when it is

**Comment by rshmiel** [comment]
@ericgomes56 @coolhitaga  Hey,
we have just merged this PR: #184 
@KoppulaRajender FYI

**Comment by coolhitaga** [comment]
thanks @rshmiel @ericgomes56 @KoppulaRajender
