### ISSUE TITLE
indentation issue, should be indent 10 and not 12

### ISSUE THREAD

**Issue by alexinthesky** [aquasecurity/aqua-helm#154]
https://github.com/aquasecurity/aqua-helm/blob/2c1ccf41702c6cd153c95f4a949c95a36b0f1f57/scanner/templates/scanner-deployment.yaml#L68

**Comment by KoppulaRajender** [comment]
Hi @alexinthesky, Thanks for writing. 
Raised a PR for the fix PR: https://github.com/aquasecurity/aqua-helm/pull/167
