### ISSUE TITLE
Template Envoy Config gateway-headless-svc to include Release.Namespace

### ISSUE THREAD

**Issue by mitchellmaler** [aquasecurity/aqua-helm#161]
Currently the envoy config is hard coding the namespace that the gateway-headless-svc would be in and if you deploy aqua into a different namespace other than "aqua" envoy will not work.

Need to update
`address: {{ .Release.Name }}-gateway-headless-svc.aqua.svc.cluster.local`
to 
`address: {{ .Release.Name }}-gateway-headless-svc.{{ .Release.Namespace }}.svc.cluster.local`

**Comment by rshmiel** [comment]
Fixed. @mitchellmaler thanks for your input.
