### ISSUE TITLE
Documentation for db.passwordSecret is incorrect

### ISSUE THREAD

**Issue by QuentinBisson** [aquasecurity/aqua-helm#197]
In the [aqua server](https://github.com/aquasecurity/aqua-helm/blob/master/server/README.md)  and [gateway](https://github.com/aquasecurity/aqua-helm/blob/master/gateway/README.md) documentation, the property `db.passwordSecret` is documented as `password secret name` when this property is used as a flag to know if the user specified a password in the values file and not as the password secret name (cf. https://github.com/aquasecurity/aqua-helm/blob/3b3c7746ec807d6949323bb006a99589f32b4714/server/templates/db-deployment.yaml#L34).

**Comment by KoppulaRajender** [comment]
@QuentinBisson  - we have fixed the issue in #208, now it will be clear to use the DB passwords from secrets.
