### ISSUE TITLE
web-secret.yaml in aqua-helm/server has duplicate keys

### ISSUE THREAD

**Issue by jpecora716** [aquasecurity/aqua-helm#200]
The following code is listed twice as part of web-secret.yaml in aqua-helm/server

metadata:
  name: {{ .Release.Name }}-console-secrets

It's preventing me from writing kustomize scripts due it being invalid yaml:
$> kustomize build
2021/02/20 10:11:17 failed to decode ynode: yaml: unmarshal errors:
  line 11: mapping key "metadata" already defined at line 4
$> kustomize version
{Version:kustomize/v4.0.1 GitCommit:516ff1fa56040adc0173ff6ece66350eb4ed78a9 BuildDate:2021-02-13T21:21:14Z GoOs:linux GoArch:amd64}

We're still using the 5.0.0 chart, would it be possible to update that chart as well?

Thanks

**Comment by rshmiel** [comment]
@jpecora716 thanks for reporting, see #201 for more information.
