### ISSUE TITLE
Web Secrets: Duplicated metadata.name field

### ISSUE THREAD

**Issue by AdrienneCohea** [aquasecurity/aqua-helm#209]
In https://github.com/aquasecurity/aqua-helm/blob/5.3/server/templates/web-secrets.yaml#L12-13, latest commit 70ae917, it appears that `.metadata` and `.metadata.name` are duplicated. This causes an error when used with kustomize:

```
failed to decode ynode: yaml: unmarshal errors:
  line 11: mapping key "metadata" already defined at line 4.
```

**Comment by KoppulaRajender** [comment]
@AdrienneCohea - Fixed the bug in the following PR #208
