### ISSUE TITLE
Server: Image pull secret name does not match service account

### ISSUE THREAD

**Issue by AdrienneCohea** [aquasecurity/aqua-helm#215]
On branch 5.3, as of commit e1da7fc, the image pull secret name uses `.Release.Name` (https://github.com/aquasecurity/aqua-helm/blob/5.3/server/templates/image-pull-secret.yaml#L6), but the service account expects the secret name to be built from `.Release.Namespace` (https://github.com/aquasecurity/aqua-helm/blob/5.3/server/templates/serviceaccount.yaml#L13).

For reference, the enforcer chart is more consistent on this: https://github.com/aquasecurity/aqua-helm/blob/5.3/enforcer/templates/serviceaccount.yaml#L14 and https://github.com/aquasecurity/aqua-helm/blob/5.3/enforcer/templates/image-pull-secret.yaml#L6

I defer to you on which name you'd like to use, `.Release.Namespace` or `.Release.Name`, but I have a slight preference for `.Release.Name` (what if a user wants to deploy different charts to the same namespace?)

The impact of this that `imageCredentials.create` must be set to `false` in order to work correctly, and the secret must be created by the user out-of-band.

**Comment by rshmiel** [comment]
@AdrienneCohea the issues were fixed and merged
