### ISSUE TITLE
Multiple issues - scanner and gateway

### ISSUE THREAD

**Issue by techish-io** [aquasecurity/aqua-helm#228]
For scanner connectivity to aqua server API you have hardcoded HTTP protocol, please parameterize it as in our case we have it over HTTPS and I have to edit your template to make it work for us

https://github.com/aquasecurity/aqua-helm/blob/5.3/scanner/templates/scanner-deployment.yaml#L51

**Comment by KoppulaRajender** [comment]
added support in #231
