### ISSUE TITLE
kube-enforcer service-account name hardcoded

### ISSUE THREAD

**Issue by kclarkey** [aquasecurity/aqua-helm#232]
https://github.com/aquasecurity/aqua-helm/blob/076934b11e879e4ec623a243313699c5b0f76f0c/kube-enforcer/templates/service-account.yaml#L5

This should probably reference the provided value:
```yaml
 name: {{ .Values.serviceAccount.name }}
```

Noticed in both the 5.3 branch and 6.0 (referenced above)

**Comment by KoppulaRajender** [comment]
Thanks for addressing the issue, fixed in https://github.com/aquasecurity/aqua-helm/pull/268
