### ISSUE TITLE
Enforcer - Autogenerated Service Account does not match Service Account Name referenced in deployment

### ISSUE THREAD

**Issue by kclarkey** [aquasecurity/aqua-helm#233]
Daemonset assumes SA name generated from namespace-name
https://github.com/aquasecurity/aqua-helm/blob/076934b11e879e4ec623a243313699c5b0f76f0c/enforcer/templates/enforcer-daemonset.yaml#L28

SA assumes name generated from release-name
https://github.com/aquasecurity/aqua-helm/blob/076934b11e879e4ec623a243313699c5b0f76f0c/enforcer/templates/serviceaccount.yaml#L5

**Comment by KoppulaRajender** [comment]
As part of https://github.com/aquasecurity/aqua-helm/commit/8b4777f4750115c1a4d965a3407de84725b574a2 we have fixed the SA name bug across all charts.

**Comment by kclarkey** [comment]
> As part of [8b4777f](https://github.com/aquasecurity/aqua-helm/commit/8b4777f4750115c1a4d965a3407de84725b574a2) we have fixed the SA name bug across all charts.

I see that fix in the 5.3 branch, but it doesn't look like it made it into the 6.0 branch. (sorry for not making that distinction explicit in the comment above).
