### ISSUE TITLE
Bump chart version on changes

### ISSUE THREAD

**Issue by joaovitor** [aquasecurity/aqua-helm#244]
There are changes being made in 5.3 branch that does not bump patch chart version.

This brings problems to mirror aquasec repository.

Can you start use https://github.com/helm/chart-testing-action ?

A good example of this being used can be found here:
https://github.com/kubernetes/autoscaler/blob/master/.github/workflows/pr.yaml#L17-L45

**Comment by agilgur5** [comment]
Mentioned back in #82 as well
