### ISSUE TITLE
service account name mismatch 

### ISSUE THREAD

**Issue by ahmei0** [aquasecurity/aqua-helm#276]
gateway deployment is failing because service account is created with the name 

{{ .Release}}-sa but referred as {{ .Release.Namespace }}-sa

https://github.com/aquasecurity/aqua-helm/blob/6.0/gateway/templates/serviceaccount.yaml#L5

https://github.com/aquasecurity/aqua-helm/blob/6.0/gateway/templates/gate-deployment.yaml#L29

**Comment by rshmiel** [comment]
The issue was fixed. see attached PRs.
@ahmei0 FYI
