### ISSUE TITLE
Unable to find command to install acqusec for the first time

### ISSUE THREAD

**Issue by krdpk17** [aquasecurity/aqua-helm#29]
Hello,
  Greetings. I am trying to install helm-chart in my k8s environment. I expected that document should have 'helm install' command. But I didn't find it. Document is mentioning about 'helm upgrade --install'. 
Can you please help to get the relevant guide.

Regards,
Deepak

**Comment by niso120b** [comment]
you can use 
`helm upgrade --install`
also for first time installation, and if its exist then its upgrade
