### ISSUE TITLE
Proposal: Support for console AQUA_PUBSUB_DBSSL environment variable

### ISSUE THREAD

**Issue by tannerwatson** [aquasecurity/aqua-helm#290]
This is a proposal for the support of configuring  the `AQUA_PUBSUB_DBSSL` environment variable in the same method as `SCALOCK_DBSSL` with `db.ssl` and `SCALOCK_AUDIT_DBSSL` with `db.auditssl` for consistency.

Currently, this can be configured with `web.extraEnvironmentVars` but is inconsistent.

I'll try to submit a PR this weekend, but I'm a helm authoring noob.

**Comment by KoppulaRajender** [comment]
Thanks for reporting.
Added requested support in all active branches. Closing the issue.
