### ISSUE TITLE
"A valid .Values.certsSecret.serverCertificate entry required" even when create is set to False

### ISSUE THREAD

**Issue by beachfires** [aquasecurity/aqua-helm#318]
https://github.com/aquasecurity/aqua-helm/blob/b582902c4973c3892192edb7e5a5fb6eebc2e4ca/kube-enforcer/templates/kube-enforcer-certs.yaml#L4

I'm getting a `Error: Failed to render chart: exit status 1: Error: execution error at (kube-enforcer/templates/_helpers.tpl:39:17): A valid .Values.certsSecret.serverCertificate entry required` error message even when `certsSecret.create` is set to False. This shouldn't be the case as the serverCertificate and serverKey values are not used.

**Comment by KoppulaRajender** [comment]
Hi @beachfires, for kube-enforcer it is mandatory to load certificates. please check https://github.com/aquasecurity/aqua-helm/tree/6.2/kube-enforcer#configurable-parameters for mandatory variables.

here, if certs are loading from existing certs, need to provide that secret name at  .Values.certsSecret.name and make .Values.certsSecret.create  to false or If loading certs from base64 values providing in values.yaml then need to make  .Values.certsSecret.create to true and mention the name for the secrets.

**Comment by rshmiel** [comment]
closing...

**Comment by rshmiel** [comment]
closing
