### ISSUE TITLE
Incorrect reference to image pull secret

### ISSUE THREAD

**Issue by beachfires** [aquasecurity/aqua-helm#322]
https://github.com/aquasecurity/aqua-helm/blob/2a8ffad2d6afbea2f70ad938e6581c8bd5786839/server/templates/serviceaccount.yaml#L13

You're using `Release.name` whereas your [image pull secret](https://github.com/aquasecurity/aqua-helm/blob/6.2/server/templates/image-pull-secret.yaml) template uses the naming `Release.namespace`. This is the same problem which happened with version 6.0.

**Comment by jg0rd042** [comment]
Same problem around here. Any solution?. 

Would it be related to this problem?

`Failed to pull image "[private-registry]/aqua-gateway:6.2.21171": rpc error: code = Unknown desc = Error response from daemon: Get https://[private-registry]/aqua-gateway/manifests/6.2.21171: unknown: Authentication is required `

Some context. I have verified that the credentials are correct (they are those of the private registry). With version 5.3 it worked correctly, when updating the HelmChart to version 6.2 and the image to 6.2 is when the error has appeared

**Comment by beachfires** [comment]
@jg0rd042 A temporary solution would be to copy the helm charts locally and fix the naming error which I pointed out. Otherwise you can upgrade to 6.0.2 for the time being, until they fix this bug.

**Comment by jg0rd042** [comment]
That has worked. Thank you for your quick and accurate response.

**Comment by KoppulaRajender** [comment]
Thanks for reporting, Added a fix for the 6.2 branch [here](https://github.com/aquasecurity/aqua-helm/pull/323)

**Comment by KoppulaRajender** [comment]
PR is merged, closing this issue.
