### ISSUE TITLE
Is note possible to deploy just the enforcers using helm

### ISSUE THREAD

**Issue by tectime** [aquasecurity/aqua-helm#371]
It is not possible to deploy just Aqua Enforcers using Helm.

When I tried to deploy only Enforcers using the Helm charts provided here, after deployment I couldn't find the enforcers installed in the aqua namespace or any other namespace.

**Comment by jg0rd042** [comment]
I am using helm to only deploy the enforces and it works correctly, could you give some more information? the helm command you use and the values.yaml

**Comment by semyonmor** [comment]
@tectime do you still experience the issue with deployment only enforcer using helm chart?
if yes, please add more details and we will try to help you. currently, we do not see any problem to deploy enforcers separately on a different cluster.
And if everything is ok, pls close the issue :)

**Comment by semyonmor** [comment]
We are closing the current issue because not see any problem from our side to deploy enforcer using a separate helm chart
IF you still think that we have a problem please open a new issue with the details.
