### ISSUE TITLE
Enforcer DaemonSet missing tolerations configuration

### ISSUE THREAD

**Issue by mitchellmaler** [aquasecurity/aqua-helm#443]
The enforcer DaemonSet manifest is missing anyway to configure tolerations other than the really old annotation method if you k8s env is 1.6 or less. That annotation should be removed and a toleartions property should be added since it does exist in the values.yaml.

**Comment by semyonmor** [comment]
Fixed as part of PR https://github.com/aquasecurity/aqua-helm/pull/447
Thank you for help
