### ISSUE TITLE
Feature Request - Add option to have priorityclass

### ISSUE THREAD

**Issue by vikas027** [aquasecurity/aqua-helm#452]
Aquasec Enforcer is one of the most critical pods, it would be great to have an option to put priority class in the [values](https://github.com/aquasecurity/aqua-helm/blob/6.5/enforcer/values.yaml) file.

**Comment by semyonmor** [comment]
Hi @vikas027 
The priorityClass is a non-namespaced object. https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass 
I think that cluster administrator should manage it and not by us

**Comment by vikas027** [comment]
Yes, I understand it is a cluster scoped resource but will it not be better to have the priority of the pods as high or critical.

And yes, this is the task of cluster admin, all I am asking is to to enable an option to do the same, so that one can specify the same in the helm values.
