### ISSUE TITLE
Vault and AquaSec Enforcer

### ISSUE THREAD

**Issue by rumstead** [aquasecurity/aqua-helm#458]
Hello all,

I am wondering how everyone is securely deploying the AquaSec Enforcer. The helm chart is forcing it to come from a [Kubernetes secret](https://github.com/aquasecurity/aqua-helm/blob/89674ba5b953f52741e85f9517ed66768e790fde/enforcer/templates/enforcer-daemonset.yaml#L39). That makes using Vault and or other secret managers difficult. Additionally, there is no way to [add annotations](https://github.com/aquasecurity/aqua-helm/blob/89674ba5b953f52741e85f9517ed66768e790fde/enforcer/templates/enforcer-daemonset.yaml#L17) via the values.yaml. 

Am I missing something? Can I contribute a patch here to "turn off" the secret and add annotations? 

I am assuming I could probably get around the secret issue by creating a fake secret and having the vault agent sidecar override it, though I haven't tried it.

**Comment by semyonmor** [comment]
@rumstead 
Currently, we are supporting Enforcer token via Kubernetes secret.
Regarding the annotation option, you absolutely right, we will add it as soon as we can and update you

**Comment by rumstead** [comment]
> @rumstead Currently, we are supporting Enforcer token via Kubernetes secret.

Yup I can see that via the chart. To deploy the token in a secure manner, doesn't it make sense to use a secret management system? Our team uses GitOps and in order to deploy secrets, we use Vault. Because the chart forces you to use a secret, it makes it almost impossible to use Vault as a secret manager.

**Comment by semyonmor** [comment]
@rumstead 
Almost or impossible?
How can we help you? The default option is to use Kubernetes secret
I understand that your DevOps team using Vault, another team will use sealedSecret, and maybe someone will use AWS Secret Manager.

**Comment by rumstead** [comment]
Vault doesn't create actual Kubernetes secrets (yet). It uses a mutating webhook to inject a sidecar/init container that will expose the secret via environment variables or files to the main container. Essentially what is done with a Kubernetes secret. AFAIK, AWS Secret Manager and Azure Key Vault do the same thing but I know all the secret management solutions are looking to use the [Secret store CSI driver](https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret.html) which I believe will use native Kubernetes Secrets backed by the driver. 

What I suggest is the ability to turn off the secret creation via a flag in the `values.yaml`.

I have an untested workaround I plan to try. 
1. Have the chart create the secret with a dummy value. Ie set [this](https://github.com/aquasecurity/aqua-helm/blob/89674ba5b953f52741e85f9517ed66768e790fde/enforcer/templates/enforcer-token-secret.yaml#L14) to "hello world"
2. Have Vault override the `AQUA_TOKEN ` environment variable to the value it has stored. Effectively ignoring the "hello world" value.

**Comment by rumstead** [comment]
Sadly, Vault also requires you to override the command of the container to first export any secrets as environment variables. So that would need to be templated out as well. 

https://www.vaultproject.io/docs/platform/k8s/injector/examples#environment-variable-example
