### ISSUE TITLE
Allow adding annotations to the kube-enforcer Validating and Mutating Webhook so CertManager can inject the CA Bundle

### ISSUE THREAD

**Issue by mitchellmaler** [aquasecurity/aqua-helm#459]
We are using Cert Manager and most of the time use it to automatically rotate and inject certs for the kubernetes webhook configurations. https://cert-manager.io/docs/concepts/ca-injector/
This requires you to provide annotations to the webhook resources that way it knows what cert to inject. In the values it does call out using cert manager but I don't think it is possible to use it without annotations.
Can this be added to the templates?

https://github.com/aquasecurity/aqua-helm/blob/6.5/kube-enforcer/templates/mutating-webhook.yaml
https://github.com/aquasecurity/aqua-helm/blob/6.5/kube-enforcer/templates/validating-webhook.yaml

**Comment by semyonmor** [comment]
@mitchellmaler 
We've added the annotations section to our kube-enforcer chart and new versions released
Thank you
