### ISSUE TITLE
Multiple issues in chart

### ISSUE THREAD

**Issue by rgarcia89** [aquasecurity/aqua-helm#461]
Link to values is wrong - global twice in path name:
https://github.com/aquasecurity/aqua-helm/blob/0a389a1f266a9abddf2004fba74d89f3e0ac23ed/server/templates/web-deployment.yaml#L67
https://github.com/aquasecurity/aqua-helm/blob/0a389a1f266a9abddf2004fba74d89f3e0ac23ed/server/templates/web-deployment.yaml#L68
https://github.com/aquasecurity/aqua-helm/blob/0a389a1f266a9abddf2004fba74d89f3e0ac23ed/server/templates/web-deployment.yaml#L89
https://github.com/aquasecurity/aqua-helm/blob/0a389a1f266a9abddf2004fba74d89f3e0ac23ed/server/templates/web-deployment.yaml#L90

Chart is missing gateway part.
I can be defined in the values but the deployment yaml are missing for it. In version 6.2 the gateway as still part of the deployment.

**Comment by semyonmor** [comment]
@rgarcia89 Thank you for your help
This issue fixed and updated chart released

**Comment by rgarcia89** [comment]
Hi @semyonmor the template files for the gateway are still missing?

**Comment by semyonmor** [comment]
@rgarcia89 
We are using a dependency chart
When this variable gateway.enabled defined as true (default value) so the server chart will also deploy the gateway chart
If you need more explanation reach me by email

**Comment by rgarcia89** [comment]
@semyonmor same issue exists in gateway chart https://github.com/aquasecurity/aqua-helm/issues/473
