### ISSUE TITLE
Invalid Semantic Version error when deploying server chart 6.5.5 or higher

### ISSUE THREAD

**Issue by cryptk** [aquasecurity/aqua-helm#463]
Hello,

When deploying aquasec server via helm chart version 6.5.5 or higher via terraform, the following error is returned:

Error: template: server/templates/web-ingress.yaml:7:7: executing "server/templates/web-ingress.yaml" at <semverCompare ">= 22" .Capabilities.KubeVersion.Minor>: error calling semverCompare: Invalid Semantic Version

It appears that the version comparison is not providing a valid semantic version to the semverCompare function.

**Comment by KoppulaRajender** [comment]
Hi @cryptk - Thanks for reporting, Added a fix for this in https://github.com/aquasecurity/aqua-helm/pull/469

**Comment by semyonmor** [comment]
Hi @cryptk
The updated helm chart was built. You can update the repo and use it
Thank you
