### ISSUE TITLE
Feature: Possibility to retain db pvcs

### ISSUE THREAD

**Issue by Volkimd** [aquasecurity/aqua-helm#466]
Hi,

I think a good thing will  be the possibility to keep database pvc in case of server deletion if internal db will be used.

A solution will be a value for db pvc keep which is default set to true.

**Comment by semyonmor** [comment]
@Volkimd 
Do you mean to keep the database volume after deleting the server helm chart?
You can define the reclaimPolicy in storageClass to be Retain and it will keep the volume after PVC deleteed

**Comment by Volkimd** [comment]
@semyonmor 
Yes. But I think if it is handled by pv reclaim policy it will be difficult to reattach the pv.
If it is handled by helm it seems to be possible to keep resources with annotation.
`"helm.sh/resource-policy": keep`
If it could be set on pvc the whole volume information will stay it is easy to reattach this pvc to pod.

**Comment by semyonmor** [comment]
....
The annotation `"helm.sh/resource-policy": keep` instructing Helm to skip deleting this resource when a helm operation (such as helm uninstall, helm upgrade, or helm rollback) would result in its deletion. However, this resource becomes orphaned. Helm will no longer manage it in any way. This can lead to problems if using helm install `--replace` on a release that has already been uninstalled but has kept resources.
....
Looks like it will create more problems than will solve. The maximum that we can do is to provide the possibility to add annotations to `pvc` and then up to you if define there something or not. 
In any case not sure that it good idea and better or keep volume by ReclaimPolicy or use db backup
