### ISSUE TITLE
bug: error with starboard-operator namespace configuration

### ISSUE THREAD

**Issue by Volkimd** [aquasecurity/aqua-helm#467]
after helm deployment startboard-operater spawns a scan process in wrong namespace.

There a more problems:

1. aqua Namespace is hardcoded in starboard-conftest-config.yaml which runs in an error regarding availability of aqua namespace
2. starboard account will be created in  namespace ".Release.Name"
3. I am not sure but I think starboard account should be created in operator value OPERATOR_TARGET_NAMESPACES

**Comment by KoppulaRajender** [comment]
@Volkimd - Thanks for reporting, added fix in https://github.com/aquasecurity/aqua-helm/pull/470

**Comment by semyonmor** [comment]
@Volkimd 
The updated helm chart was built
Thank you
