### ISSUE TITLE
bug: no possibility to deploy gateway via nodePort

### ISSUE THREAD

**Issue by Volkimd** [aquasecurity/aqua-helm#468]
You can define nodeports and service type nodeport in values but there is use of value type nodeport because clusterip is hardcoded in templates/gate-headless-service.yaml

**Comment by KoppulaRajender** [comment]
@Volkimd - Gateway service spec can be changed from Values.yaml.
headless service of the gateway is used when Envoy is deployed and acts as a proxy between enforcers/agents and gateway.
You can disable headless-service for gateway by disabling https://github.com/aquasecurity/aqua-helm/blob/7a85039cf50e657be415441770549d5c5e35b3ae/server/values.yaml#L176, If not using envoy in your deployment.

**Comment by Volkimd** [comment]
@KoppulaRajender 
oh sorry my fail. Thanks a lot. This is working fine

**Comment by Volkimd** [comment]
Solution works perfect
