### ISSUE TITLE
server chart gateway deployment with wrong serviceaccount

### ISSUE THREAD

**Issue by Volkimd** [aquasecurity/aqua-helm#476]
Hi,

there is an issue with gateway deployment via server chart.
It seems that there is not the Release Namespace is used for serviceaccount concartination
Gateway comes up with aqua-sa. ServiceAccount is aquasec-sa

**Comment by semyonmor** [comment]
@Volkimd 
Once again thank you for help.
The database issue was solved with this [PR](https://github.com/aquasecurity/aqua-helm/pull/474)
Regarding the gateway serviceAaccount.
It could be controlled or via parent server chart using `gateway.serviceAccount.create` and  `gateway.serviceAccount.name` variables. By default it will be created with the name `aqua-sa`
