### ISSUE TITLE
Possible values for logLevel are not specified on the enforcer README file

### ISSUE THREAD

**Issue by violiveira** [aquasecurity/aqua-helm#479]
As can be see on this line: https://github.com/aquasecurity/aqua-helm/blob/6.5/enforcer/values.yaml#L37

`logLevel` is a configurable field via the values.yaml file. However, there is no mention of this fields on the README file: https://github.com/aquasecurity/aqua-helm/blob/6.5/enforcer/README.md

For the sake of formality, it would be good to have the possible values for this fields described on README, as it happens for all other fields.

**Comment by KoppulaRajender** [comment]
@violiveira - For Enforcer now has a standard logging level and is not required to override the value. Removed the parameter from values.yaml #480 

Thanks for raising this :+1:

**Comment by RohanArya4894** [comment]
Hi @KoppulaRajender , how can I override the logLevel to WARN if this is removed from values.yaml.
