### ISSUE TITLE
Harcoded serviceAccountName in gateway deployment

### ISSUE THREAD

**Issue by dudniksergei** [aquasecurity/aqua-helm#482]
look at the files:
aqua-helm/gateway/values.yaml:
`
serviceAccount:
 ​create: false
 ​name: "aqua-sa"
`
aqua-helm/gateway/templates/gate-deployment.yaml:
`
      serviceAccount: {{ .Values.serviceAccount.name }}
`

but  in aqua-helm/server/templates/serviceaccount.yaml

`
---
apiVersion: v1
kind: ServiceAccount
metadata:
{{- with .Values.serviceaccount.annotations }}
 ​annotations:
{{ toYaml . | indent 4 }}
{{- end }}
 ​name: {{ .Release.Namespace }}-sa
`
so if I use name for namespace aqua-test, server chart create serviceaccount with name "aqua-test-sa" but gateway chart create deployment with  serviceaccount name "aqua-sa", so gateway pod cant start due serviceaccount's name mismatch.

Coud you please  use aqua-sa always for all chart with any namespace name or fix gateway serviceaccount name.

**Comment by semyonmor** [comment]
HI @dudniksergei 

Currently, we are using the server and gateway charts as parent and child charts.
When you create the gateway with server parent chart so both components will use the same serviceAccount
But If you want to create a separate serviceAccoint for gateway, you can control it by using
gateway.Values.serviceAccount.create and gateway.Values.serviceAccount.name.

**Comment by dudniksergei** [comment]
> When you create the gateway with server parent chart so both components will use the same serviceAccount

No. I try it with namespace named aqua-test. So sa "aqua-test-sa" had been created, but gateway deployment  wanted  sa "aqua-sa"
