### ISSUE TITLE
Can't get the info in Readme to work

### ISSUE THREAD

**Issue by cseader** [aquasecurity/aqua-helm#5]
Are there updated instructions?

Also noticed the latest Pull request from a few days ago. I tried the chart repository, but it doesn't seem to work either. Can you give me a status on this. I'd like to give this a go running on top of openSUSE Kubic and SUSE CaaS Platform.
Thanks,
Cameron

**Comment by jmichealson** [comment]
> Are there updated instructions?
> 
> Also noticed the latest Pull request from a few days ago. I tried the chart repository, but it doesn't seem to work either. Can you give me a status on this. I'd like to give this a go running on top of openSUSE Kubic and SUSE CaaS Platform.
> Thanks,
> Cameron

This repo has been updated significantly.  Closing this issue.
