### ISSUE TITLE
Gateway enable support for loadBalancerSourceRanges

### ISSUE THREAD

**Issue by darkdatter** [aquasecurity/aqua-helm#536]
Currently, the [Aqua Gateway chart](https://github.com/aquasecurity/aqua-helm/blob/6.5/gateway/templates/gate-service.yaml) supports a user's choice between `ClusterIP `or `LoadBalancer`. However, When using `type: LoadBalancer `, the chart does not support the use of `loadBalancerSourceRanges` to limit the IPs which can communicate with the public `LoadBalancer`.

I propose adding support to the `../6.5/gateway/templates/gate-service.yaml` for this. I can submit the PR if others agree with this change.

**Comment by KoppulaRajender** [comment]
Hi @darkdatter, we can use service annotations to add loadBalancerSourceRanges. [docs link](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/#access-control)

and aqua gateway charts support adding annotations to the service. If you want to add `loadBalancerSourceRanges` at the service spec level please raise a PR and we will review it.

**Comment by semyonmor** [comment]
@darkdatter A gentle reminder

**Comment by semyonmor** [comment]
hi @darkdatter as we said in our previous comment you can add the load balancer source range via the annotation, see [example](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/#access-control) 
if it not something that you looked for, please reopen this issue
