### ISSUE TITLE
Add PriorityClass option to Aqua Enforcer Pod Spec

### ISSUE THREAD

**Issue by mitchellmaler** [aquasecurity/aqua-helm#537]
Right now there isn't a PriorityClass specified for the Aqua Enforcer which means it could be evicted by the kubelet before other non-critical pods. I would like to request adding PriorityClass option to the daemonset which then can be passed in from the helm values.

**Comment by mitchellmaler** [comment]
@semyonmor You added a way to create a priorityClass but never added an option in the enforcer-ds to specify the priorityClass name. The values should have a way to specify an existing priorityClass or create a new one and then set that on the enforcer ds pods.

**Comment by KoppulaRajender** [comment]
https://github.com/aquasecurity/aqua-helm/pull/551 - fix
