### ISSUE TITLE
Feature: Support reloading TLS certificate secret changes in the kube-enforcer pod

### ISSUE THREAD

**Issue by pmcgrath** [aquasecurity/aqua-helm#562]
I'm currently seeing that when the certificate is changed in the mounted secret for the **kube-enforcer** pods it does not seem to result in the svc/pod reloading the new certificate.

We use cert-manager to generate the TLS certificate used for the validating/mutating webhooks with short a duration and have observed the secret is updated as expected, we have also confirmed the mounted secret is also updated as expected, but the webhooks continue to serve the certificate that was present when the pod was started, so I suspect the image binary does not watch the path for changes and reload it. Can see cert-manager is also updating the webhook caBundle as expected.

This results in webhook failures which we have observed on the k8s apiserver logs, as soon as the cert secret is updated

Compared the secret cert and the served certificate with - replace the SOME_NS SOME_POD_NAME refs
```
# Run this on a pod with oepnssl on it to get the served certificate
kubectl exec -n SOME_NS SOME_POD_NAME -- /bin/sh -c "echo | openssl s_client -showcerts -connect aqua-kube-enforcer.aqua.svc:443 2>&1 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'" > /tmp/webhook-served-server.crt

# Run this on one of the aqua kube-enforcer pods
kubectl exec -n aqua SOME_POD_NAME -- /bin/sh -c "cat /certs/${secret_server_cert_name}" > /tmp/webhook-on-disk-server.crt

# Compare and they are different
cmp -s /tmp/webhook-on-disk-server.crt /tmp/webhook-served-server.crt
[[ $? == 0 ]] && echo "DIFF"
```

We can get around this for now by using a longer duration when generating the certs

**Comment by semyonmor** [comment]
@pmcgrath 
Sorry for the delay with the response.
Can you please take it with your support engineer and open the RFE to the dev team?
