### ISSUE TITLE
Installing Quick start on OpenShift

### ISSUE THREAD

**Issue by mtcolman** [aquasecurity/aqua-helm#604]
Hi, in order to install the quick-start on OpenShift, I have had to add the serviceAccounts to the nonroot SCC binding as follows, prior to installation:
```
oc adm policy add-scc-to-user nonroot system:serviceaccount:aqua:aqua-sa
oc adm policy add-scc-to-user nonroot system:serviceaccount:aqua:aqua-kube-enforcer-sa 
```

Can you please update your documentation to reflect this? Thanks.

**Comment by semyonmor** [comment]
Hi @mtcolman 
The QuickStart scripts do not support the Openshift platform, and some important parts of the deployment are not there.
You can use the specific charts for components and deploy them one by one or use Aqua OCP Operator
