### ISSUE TITLE
server ingress fails to install/upgrade

### ISSUE THREAD

**Issue by kcorupe** [aquasecurity/aqua-helm#66]
Latest chart 4.5 fails to create ingress

```
helm upgrade --install --namespace aqua csp aqua-helm/server/ -f aqua-helm/values.yaml
UPGRADE FAILED
Error: unable to recognize "": no matches for kind "Ingress" in version "apps/v1"
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Ingress" in version "apps/v1"
```

Values.yaml (ingress section)

```
web:
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
    - aquasec.domain.com
    tls:
    - secretName: aquasec-tls
    - hosts:
      - aquasec.domain.com
```

**Comment by bernieatwar** [comment]
Any work around found for this issue yet?

**Comment by kcorupe** [comment]
I disabled ingress in aqua chat and created it manually after. Still waiting on fix from them.

**Comment by shayfisher** [comment]
They should use v1beta1 as Ingress isn't yet GA - even in k8s version 1.16.x.
You could edit a local copy of the template to reflect the change e.g revert commit:658ba37
On the server/templates/web-ingress.yaml file

**Comment by pbrit** [comment]
FYI: #70 fixes the issue.
