### ISSUE TITLE
Gateway chart/template doesn't support loadBalancerSourceRanges for IP restrictions

### ISSUE THREAD

**Issue by darkdatter** [aquasecurity/aqua-helm#675]
Within the [Gateway chart/template](https://github.com/aquasecurity/aqua-helm/blob/2022.4/gateway/templates/gate-service.yaml): there is no support for adding the list of restricted IPs via `loadBalancerSourceRanges`. There should be a conditional statement that IF `type: LoadBalancer` is set, and `loadBalancerSourceRanges` is present with a list of IPs to set on the cloud service provider's load balancer,  then they be included in the chart template file so that the load balancer/ingress controller will set them. 

E.g. in AWS, this would set those restricted IPs into a Security Group that is applied to the load balancer in front of an ingress controller.

**Comment by BaruchBilanski** [comment]
Hi @darkdatter 
Thank you for your request. We have added the necessary support for adding the list of restricted IPs via loadBalancerSourceRanges in the Gateway chart/template.

To implement this, we added a conditional statement that checks for the presence of loadBalancerSourceRanges and includes them in the chart template file when type: LoadBalancer is set.
We have also updated our documentation to reflect this change and added a section on how to use loadBalancerSourceRanges to restrict access to the Gateway. Please let us know if you have any further questions or if there is anything else we can do to assist you. Thank you for bringing this to our attention.

This is the merged PR with the changes:
https://github.com/aquasecurity/aqua-helm/pull/685
