### ISSUE TITLE
Clean up files after uninstalling Enforcer chart

### ISSUE THREAD

**Issue by KouriR** [aquasecurity/aqua-helm#681]
The Enforcer install leaves behind files on the host that aren't cleaned up after the helm chart is uninstalled, for example, in /var/lib/aquasec.

Is it possible to add a post-delete hook to the chart which runs /var/lib/aquasec/uninstall.sh on the host?

**Comment by semyonmor** [comment]
Hey @KouriR 

After some tests, we have determined that this request cannot be fulfilled via the deployment process alone and would require intervention from the development team. Would you be so kind as to open an RFE with the support or architect you are currently working with?
