### ISSUE TITLE
Ability to provide labels for kube-bench jobs, and refactor values

### ISSUE THREAD

**Issue by andreazorzetto** [aquasecurity/aqua-helm#688]
The kube-enforcer helm charts doesn't provide many options for customisation of the kube-bench jobs.
The only configurable values are: [scanTainted](https://github.com/aquasecurity/aqua-helm/blob/2022.4/kube-enforcer/values.yaml#L88) and [skipNodes](https://github.com/aquasecurity/aqua-helm/blob/2022.4/kube-enforcer/values.yaml#L99) (which btw should be moved under [kubeBench](https://github.com/aquasecurity/aqua-helm/blob/2022.4/kube-enforcer/values.yaml#L87))

Some infrastructure teams have label requirements for deployment, which cannot be met since kube-bench jobs can be customised any further and labels cannot be attached.

**Comment by BaruchBilanski** [comment]
Hi,
As much as we know, the Kube-Bench is triggered from the KE code, 
and if there is a need to change something with the deployment please take it up with the Development team.

**Comment by semyonmor** [comment]
@andreazorzetto 
I checked once again with the DEV team responsible for kube-bench deployment and this request is currently not supported. You can take it with them and open RFE
