### ISSUE TITLE
Variable global.enforcer.enabled is not documented for 'enforcer' chart

### ISSUE THREAD

**Issue by vini-ppro** [aquasecurity/aqua-helm#693]
Hello,

Looking at the sample values.yaml for the 'enforcer', the variable `global.enforcer.enabled` is defined as seen on:
https://github.com/aquasecurity/aqua-helm/blob/2022.4/enforcer/values.yaml#L16

However, this variable is not defined in the documentation: https://github.com/aquasecurity/aqua-helm/tree/2022.4/enforcer#configurable-variables

I understand the reason this variable exists for the kube-enforcer chart because it is documented, but I am confused as to why it exists for the enforcer chart as well.

**Comment by semyonmor** [comment]
hi @vini-ppro 
we are using this variable to control the enforcer deployment along with the kube-enforcer
https://docs.aquasec.com/v2022.4/platform/assurance-and-enforcement/express-runtime-protection-mode/deploy-enforcers-in-express-mode/
