### ISSUE TITLE
yaml: unmarshal errors in 6.5

### ISSUE THREAD

**Issue by chrisctl** [aquasecurity/aqua-helm#699]
As per this [issue](https://github.com/aquasecurity/aqua-helm/issues/581) 

"Running the helm chart through Kustomize it gets yaml unmarshall errors due to the duplicate key in the above lines. Set statically in L47 and via the values.yaml file on L136"

This was fixed for the 2022.4 chart but was never fixed in 6.5

**Comment by chrisctl** [comment]
@semyonmor @KoppulaRajender

**Comment by semyonmor** [comment]
fixed in https://github.com/aquasecurity/aqua-helm/pull/702
