### ISSUE TITLE
Cluster Mode

### ISSUE THREAD

**Issue by amalucelli** [aquasecurity/aqua-helm#72]
Hi, I couldn't find any useful information about this environment variable `CLUSTER_MODE`. I even tried the Knowledge Base, but found nothing.

https://github.com/aquasecurity/aqua-helm/blob/07321c6ef6934a9a4a8dc97c096f10e837269037/server/templates/web-deployment.yaml#L150-L153

Is it possible to provide more information about this?

**Comment by niso120b** [comment]
docs.aquasec.com
