### ISSUE TITLE
Support persistence in Scanner

### ISSUE THREAD

**Issue by rickymulder** [aquasecurity/aqua-helm#720]
In our environment our application teams often build very large images, ranging from 2GB up to 10GB.  This has lead to issues when the scanners attempt to pull these images, sometimes causing our hosts to crash and reboot, dumping local storage.

Persistence can very easily be achieved with swapping the Deployment with a Statefulset, and including a volumeClaimTemplate.  To accomplish the same with a Deployment would require a backing storage provider that supported RWX.

PR to come.

**Comment by semyonmor** [comment]
Added https://github.com/aquasecurity/aqua-helm/blob/b22f086c53fe2bc1b8babcaa2daaf19dc48db797/scanner/values.yaml#L165
