### ISSUE TITLE
ingress resource for gateway

### ISSUE THREAD

**Issue by techish-io** [aquasecurity/aqua-helm#724]
Would love to have ingress resource installation option for gateway pretty much similar to what you have available for server console chart. That would help install gateway ingress and expose it for enforcers connectivity

**Comment by semyonmor** [comment]
hey @techish-io 
you can use for example the option `envoy.enabled=true`or `global.gateway.service.type=LoadBalancer`
in both options, the gateway IP will be exposed.

**Comment by semyonmor** [comment]
> @techish-io any update from your side?

hi @techish-io 
we replied to your issue with the below answer
"you can use for example the option envoy.enabled=trueor global.gateway.service.type=LoadBalancer
in both options, the gateway IP will be exposed."
are you looking for something different?
