### ISSUE TITLE
livenessProbe and readinessProbe for Console

### ISSUE THREAD

**Issue by amalucelli** [aquasecurity/aqua-helm#73]
Hi, I see this block code where I can input some probe for `liveness` and `readiness`, but I can't find any default value that I can use to determine if the console is healty or ready.

Is possible to know if the console implements any of those? I tried the knowledge base but couldn't find anything useful.

https://github.com/aquasecurity/aqua-helm/blob/07321c6ef6934a9a4a8dc97c096f10e837269037/server/templates/web-deployment.yaml#L175-L182

**Comment by agilgur5** [comment]
Yea, I would think that all liveness and readiness probes should be configured out-of-the-box, as they are responsible for determining application health/readiness. That's not quite something an end user should have to know about as the app needs to expose those itself.

The block of code referenced is actually visible in _all_ deployments, not just Console.

**Comment by rshmiel** [comment]
@amalucelli thanks for reporting. Fixed see above PR.

**Comment by agilgur5** [comment]
> The block of code referenced is actually visible in _all_ deployments, not just Console.

So the above PR only added probes to one deployment, the Console. Other charts here, such as the Enforcers, still [don't seem to have](https://github.com/aquasecurity/aqua-helm/blob/2ad293b8772592b162094c3eb771a4a1a3ab915b/enforcer/templates/enforcer-daemonset.yaml#L90) any probes... Should a separate issue be opened to address those...?

The PR also implemented identical liveness and readiness probes against the `/` endpoint -- do the Console and other Aqua tools not have their own dedicated healthcheck endpoints that perform appropriate status checks? (e.g. `/healthz` that checks if DB is responsive etc)
