### ISSUE TITLE
Add option to use existing secrets for credentials on codesec agent

### ISSUE THREAD

**Issue by s-baier** [aquasecurity/aqua-helm#745]
Hey!

When deploying the [codesec-agent](https://github.com/aquasecurity/aqua-helm/tree/2022.4/codesec-agent), or any other component, that requires credentials, it would be nice to point to existing secrets, that can be created by means of the user (in a secure manner), to enable gitops deployements.

As it stands for the codesec-agent, this is currently not possible.

Same goes for existing tls secrets.

I could provide a PR if necessary, if this is cool for you?

**Comment by semyonmor** [comment]
Fixed in PR #752
