### ISSUE TITLE
Update documentation for Scanner "platform" value

### ISSUE THREAD

**Issue by clausstrommer** [aquasecurity/aqua-helm#783]
The scanner `values.yaml` file contains

```
#Define this variable for openshift platform
platform: ""
```

This implies that the `platform` value is optional.  However, this value must be set as per `templates/_helpers.tpl`:

```
{{- define "platform" }}
{{- printf "%s" (required "A valid .Values.platform entry required" .Values.platform ) | replace "\n" "" }}
{{- end }}
```

If the `platform` value is required then the comment in `values.yaml` needs to be updated, as well as the assertion in `templates_helpers.tpl`.  In both cases documentation needs to be provided as to valid values for this key.

**Comment by dpaardenkooper** [comment]
Same issue here
