### ISSUE TITLE
[kube-enforcer] Unable to set resources on trivy-operator 

### ISSUE THREAD

**Issue by mkilchhofer** [aquasecurity/aqua-helm#787]
With version [2022.4.29](https://github.com/aquasecurity/aqua-helm/blob/2022.4/kube-enforcer/CHANGELOG.md#2022429--sep-26th-2023-) you migrated from Starboard to Trivy-Operator.

In our kubernetes environment we have the scrict requirement, that all Pods set correct resources (requests and limits). Trivy operator uses hardcoded empty dictionary for this:
https://github.com/aquasecurity/aqua-helm/blob/e580f4555fb3406f82d758febadc56dfa8e80107/kube-enforcer/templates/trivy-deployment.yaml#L115-L116

It would be nice if we can inject the needed resources for the pods via helm values.

**Comment by semyonmor** [comment]
Updated by PR #793
