### ISSUE TITLE
[kube-enforcer] Unable to set/inherit airgapped settings (proxy and image repository) on trivy

### ISSUE THREAD

**Issue by mkilchhofer** [aquasecurity/aqua-helm#788]
With version [2022.4.29](https://github.com/aquasecurity/aqua-helm/blob/2022.4/kube-enforcer/CHANGELOG.md#2022429--sep-26th-2023-) you migrated from Starboard to Trivy-Operator.

The OSS trivy-operator offers the ability to configure every setting of the operator and trivy itself:
https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/templates/configmaps/trivy.yaml
Unfortunately the embedded trivy-operator here doesn't support customization.

We are in a airgapped environment where connectivity to the internet is only possible via a forward proxy.
The params
- trivy.repository
- trivy.dbRepository

are hardcoded and the params

- trivy.httpProxy
- trivy.httpsProxy
- trivy.noProxy
- trivy.serverInsecure
- trivy.sslCertDir

are missing completely.

This way I assume we cannot start trivy scans as the images and the db cannot be pulled from the operator.

**Comment by deven0t** [comment]
Hi @mkilchhofer 
Sorry for the delay in the response.
Today, integration of Trivy-operator inside commercial offering only utilizes the feature of ConfigAuditing from Trivy-operator. And hence other options are not available in this embeded trivy-operator.

Any reason to use workload image scan from trivy-operator, and not from commercial flow of workload image scan via aqua scanner. 
Today, if we enable trivy-operator to perform workload image scan then result will only be stored in CRD and it will not be surfaced on Aqua UI. If you are interested to use this feature from trivy-operator then we can include these options in helm values.

If you need more clarity then feel free to open support ticket on aqua support portal.

Regards
Devendra
cc @semyonmor @adishaull
