### ISSUE TITLE
Server helm chart YAML parse error

### ISSUE THREAD

**Issue by tnycum** [aquasecurity/aqua-helm#789]
The aqua server chart version 2022.4.19 doesn't render properly and returns this error when attempting to render it using `helmfile`:

```
Error: YAML parse error on server/templates/job-check-db-upgrade.yaml: error converting YAML to JSON: yaml: line 49: did not find expected key
```

This seems to be caused by this commit: https://github.com/aquasecurity/aqua-helm/commit/35b30290cde952545e0ec5cf10986bea34bce4a3

I believe these lines are not indented properly and when I removed two spaces at the beginning of each line the YAML could render without errors.

**Comment by tnycum** [comment]
Opened PR: https://github.com/aquasecurity/aqua-helm/pull/790

**Comment by adishaull** [comment]
Fixed: https://github.com/aquasecurity/aqua-helm/commit/f408337da0b465f06e933c7e2b4c418e3d21dcca
