### ISSUE TITLE
[aqua-server] GitOps based installation with ArgoCD

### ISSUE THREAD

**Issue by maik-d** [aquasecurity/aqua-helm#799]
Hello,

I currently want to deploy Aqua (server, scanner, gateway, enforcers as well as cyber center) via a GitOps based deployment model via ArgoCD/OpenShift Gitops. In order to achieve this I want to combine custom code in the form of another helm Chart with the pre existing helm Charts from this repository. However, during the deployment of "aqua-server" I realized, that a job called "check-db-upgrade" gets rolled out. This job has the following helm annotations, in order to make sure to only deploy the job when an upgrade of the installation gets performed, but not during the initial installation.

- "helm.sh/hook": pre-upgrade
- "helm.sh/hook-weight": "0"
- "helm.sh/hook-delete-policy": before-hook-creation

The reason for skipping this job in the context of the initial installation is, that the job requires resources (a secret called "aqua-server-web-config") that only exist if the aqua server component has been deployed before.

The actual issue is related to ArgoCD and details can be found here: https://github.com/argoproj/argo-cd/issues/7536

>  Currently, argocd treats both pre-install and pre-upgrade helm hooks as PreSync hooks. However, this is not always the case.

As ArgoCD seems [to still not support the difference in Helm hooks](https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-hooks) I wanted to open this thread and ask, whether this may be solved in a different way, within the aqua-server chart? I know that for now I should be able to modify the annotations and swap them with respective ArgoCD annotations, but here the problem is, that ArgoCD itself does not differentiate between an install and upgrade.

Thus I want to make aware of this issue and maybe discuss possible solutions. Maybe someone has already run into this issue and managed to overcome it with a neat solution? Another reason for this thread is, that I want to use the upstream Helm charts without modifying them if possible, as this only increases the complexity when it comes to upgrades.

Regards,
Maik

**Comment by maik-d** [comment]
I also have a suggestion for a fix. Maybe a check for a parameter like "argoCdEnabled" could be built in. If this parameter is set to true the mentioned helm hooks will not be included in the "check-db-upgrade" job. Instead, if deployed via ArgoCD (via the mentioned parameter set to true), the "check-db-upgrade" looks for existing secrets, that only exist, if the server and db's have been deployed before (maybe also looking for the deployment or running pods). If such a proof of an existing installation can be found the job executes as expected. If such resources are not found however, the job just ends in silence (without an error) and maybe returns a small information why.

**Comment by clausstrommer** [comment]
I have this issue as well.  My temporary workaround is to stub the configmap that the server needs to run the DB job.
