### ISSUE TITLE
Active:active is enabled by default

### ISSUE THREAD

**Issue by cdunford** [aquasecurity/aqua-helm#81]
Active:active support was recently added to the server chart, and the docs indicate it is disabled by default:

https://github.com/aquasecurity/aqua-helm/commit/e688b2789620078e1a9bb931c6ab0c9559a22a13#diff-7d62b4cde47a08800e3b7212ca2dd397R81

However the default value for `activeactive` is actually `true`:

https://github.com/aquasecurity/aqua-helm/commit/ce60ce8e7fdaf83413a226846da242d7679756b5#diff-0fd8ccf1d8b0f5309cd540e606d67248R17

The default value should be `false`, as this is an unwanted new setting for existing consumers of the chart.

**Comment by agilgur5** [comment]
Looks like this was resolved in https://github.com/aquasecurity/aqua-helm/commit/75856ffe541c0d3d1f9e2029be79cfb2d8483e6e for 5.0

**Comment by xB-2048** [comment]
@cdunford Thanks for reporting the issue. 

The issue is fixed in the latest chart so moving the issue to closure.
