### ISSUE TITLE
Client request: make enforcer name configurable

### ISSUE THREAD

**Issue by jolsonaqua** [aquasecurity/aqua-helm#87]
an Aqua client has requested that an update be made to the following line:

https://github.com/aquasecurity/aqua-helm/blob/master/enforcer/templates/enforcer-daemonset.yaml#L27-28

They wish to have the name "enforcer" replaced with a helm variable that allows for a custom name. I have informed them of the ease with which this can be done in a local file and provided instruction for doing so.

This is not a request for support, but simply to update our file documentation. Thank you!

**Comment by KoppulaRajender** [comment]
Changes are in place. Closing this ticket.
