### ISSUE TITLE
Missing annotations field in values.yaml to be able to add annotations to scanner deployment

### ISSUE THREAD

**Issue by Masoud-CSIRT** [aquasecurity/aqua-helm#872]
**Description**
In values.yaml, there is no way to define annotations to the scanner deployment.

In many deployments, this is needed to be able to define custom annotations like email owner to be compliant with compny policies.

Please add the cabability to define annotations in [values.yaml](https://github.com/aquasecurity/aqua-helm/blob/2022.4/scanner/values.yaml)
After adding the annotations in values.yaml file, it must be included in the [metadata section of the scanner deployment](https://github.com/aquasecurity/aqua-helm/blob/2022.4/scanner/templates/scanner-deployment.yaml#L8) manifest.

This will have following benefits
Enhanced Customization: Users can add metadata to Kubernetes resources, tailoring deployments to specific needs without modifying the Helm chart itself.
Improved Management: Annotations can be used for tracking deployments, adding descriptive information, and managing resources more effectively.
Facilitates Integration: Enables integration with other tools and systems (e.g., monitoring, logging) that rely on annotations to function correctly.
Better Organization: Helps in categorizing and organizing resources, making it easier to manage and query them using Kubernetes selectors.

**Comment by semyonmor** [comment]
Added with #873
