### ISSUE TITLE
Security context for non-privileged deployments

### ISSUE THREAD

**Issue by VotoCopy** [aquasecurity/aqua-helm#88]
Documentation says to use certain users, group and fsgroup when running server and gateway deployments. The helm charts say to run as any hardcoded. What's the best way to do this?

{{ - if .Values.rbac.privileged }]
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
{{ - else }}
  runAsUser: 
  - {{ .Values.rbac.securityContext.runAsUser}}
  runAsGroup: 
  - {{ .Values.rbac.securityContext.runAsGroup}}
  fsGroup: 
  - {{ .Values.rbac.securityContext.fsGroup}}
{{ -end }}

values.yaml
  securityContext:
      runAsUser: 11431
      runAsGroup: 11433
      fsGroup: 11433

**Comment by KoppulaRajender** [comment]
there were a lot of changes applied with respect to RBAC on all charts.
https://github.com/aquasecurity/aqua-helm/pull/454 - This PR completely makes components run in non-privileged mode.

**Comment by semyonmor** [comment]
I'm closing this issue due to update from @KoppulaRajender
