### ISSUE TITLE
Scanner Helm Chart - Fails when enableLivenessProbe is set to true

### ISSUE THREAD

**Issue by andrewrust13** [aquasecurity/aqua-helm#909]
The Scanner Helm Chart version 2022.4.8 fails when enableLivenessProbe is set to true for multiple reasons.

Firstly the Helm values file is using incorrectly named values:

```
initial_delay_seconds: 15
period_seconds: 60
success_threshold: 1
failure_threshold: 3
timeout_seconds: 1
```

The values should be:
```
initialDelaySeconds: 15
periodSeconds: 60
successThreshold: 1
failureThreshold: 3
timeoutSeconds: 1
```

Secondly, the configmap is now invalid as you cannot have non-string values:

`AQUA_HEALTH_MONITOR_PORT: {{ .Values.livenessProbe.httpGet.port }}`

This value needs to be a string.

Not quite sure how this was tested or ever worked.

**Comment by varadaprakash** [comment]
PR #912 is merged and released in 2022.4.9
Please use 2022.4.9

Thanks
Varada Prakash
