### ISSUE TITLE
KubeEnforcer Chart doesn't exist on https://helm.aquasec.com

### ISSUE THREAD

**Issue by agilgur5** [aquasecurity/aqua-helm#96]
I was following the [directions in the README](https://github.com/aquasecurity/aqua-helm#deployment-instructions) and ran into some issues with the KubeEnforcer Chart not existing on the https://helm.aquasec.com server.

Reproduction:
```bash
$ helm repo add aqua-helm https://helm.aquasec.com
"aqua-helm" has been added to your repositories
$ helm search repo aqua-helm
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                                       
aqua-helm/enforcer              5.0.0           5.0             A Helm chart for the Aqua Enforcer                
aqua-helm/harbor-scanner-aqua   0.2.0           0.2.0           Harbor scanner adapter for Aqua CSP scanner       
aqua-helm/harbor-scanner-trivy  0.1.3           0.2.1           Trivy as a plug-in vulnerability scanner in the...
aqua-helm/scanner               5.0.0           5.0             A Helm chart for the aqua scanner cli component   
aqua-helm/server                5.0.0           5.0             A Helm chart for the Aqua Console Componants
```

There is no `aqua-helm/kube-enforcer` as the README suggests. The `kube-enforcer` Chart in the repo also has [`version: 0.1.0`](https://github.com/aquasecurity/aqua-helm/blob/2b24694eb9313742529828bf0b8d7a95d75b2af3/kube-enforcer/Chart.yaml#L5) and not `5.0.0` as the README shows and the other Charts have.

Similarly had an error when adding as a dependency to a `Chart.yaml`:
```bash
...
Saving 4 charts
Downloading server from repo https://helm.aquasec.com
Downloading scanner from repo https://helm.aquasec.com
Downloading enforcer from repo https://helm.aquasec.com
Save error occurred:  could not find : chart kube-enforcer not found in https://helm.aquasec.com
Deleting newly downloaded charts, restoring pre-update state
Error: could not find : chart kube-enforcer not found in https://helm.aquasec.com
```

**Comment by ericgomes56** [comment]
Yes, this is true and I have reproduced the behavior too.  I have raised this internally using a defect identifier for this to be resolved.

Alternatively, you can perform a 'git clone https://helm.aquasec.com' and you will receive all of the expected files and manifests.

![Screen Shot 2020-07-23 at 9 29 09 AM](https://user-images.githubusercontent.com/38416014/88301280-6e109380-ccd2-11ea-83a1-b600f28e001a.png)

**Comment by KoppulaRajender** [comment]
Closing ticket. Fix is in place.

**Comment by agilgur5** [comment]
I'm still not seeing the KubeEnforcer Chart:

```bash
$ helm repo add aqua-helm https://helm.aquasec.com
"aqua-helm" has been added to your repositories
$ helm search repo aqua-helm
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                                    
aqua-helm/enforcer              5.3.0           5.3             A Helm chart for the Aqua Enforcer             
aqua-helm/harbor-scanner-aqua   0.10.1          0.10.0          Harbor scanner adapter for Aqua CSP scanner    
aqua-helm/harbor-scanner-trivy  0.12.0          0.15.0          Harbor scanner adapter for Trivy               
aqua-helm/scanner               5.3.0           5.3             A Helm chart for the Aqua Scanner CLI component
aqua-helm/server                5.3.0           5.3             A Helm chart for the Aqua Console components   
```

The `kube-enforcer` Chart.yaml in the repo still has [`version: 0.1.0`](https://github.com/aquasecurity/aqua-helm/blob/3b3c7746ec807d6949323bb006a99589f32b4714/kube-enforcer/Chart.yaml#L5) as well
