### ISSUE TITLE
docs: unclear what the difference between Active-Active and HA Cluster Mode are

### ISSUE THREAD

**Issue by agilgur5** [aquasecurity/aqua-helm#98]
The server docs have an [`activeactive` and `clustermode` options](https://github.com/aquasecurity/aqua-helm/blob/38f48d607ca6fbda0cb29a154df9f47d3ce8bd15/server/README.md#L66) but it's not clear what the difference between the two is.

`clustermode` says it is for "HA" but `activeactive` is a term for an HA deployment as well. [A comment in the Chart values](https://github.com/aquasecurity/aqua-helm/blob/38f48d607ca6fbda0cb29a154df9f47d3ce8bd15/server/values.yaml#L15) also lists that the two are mutually exclusive with each other, which adds to the confusion. The [website's docs for HA](https://docs.aquasec.com/docs/active-active-server-mode) mention Active-Active but not "Cluster Mode" as well.

It would be good to clarify the differences between the two, whether one is deprecated or not (since the website doesn't mention cluster mode, maybe it is?), which one is _optimal_ (i.e. most resilient), and what the default is (both are `false`, so default is not HA?).

#72 is related but was not really answered. The response doesn't point to a specific place in the docs and I have read the docs; it defines these as the same thing as far as I can tell: `aqua_cluster_mode='active-active'`

**Comment by Hefeweizen** [comment]
Just encountered this myself.

activeactive equates to: https://docs.aquasec.com/docs/active-active-server-mode
clustermode equates to: https://docs.aquasec.com/docs/active-passive-server-mode-to-be-deprecated (as the section https://docs.aquasec.com/docs/active-passive-server-mode-to-be-deprecated#section-activation-of-aqua-server-failover spells out setting this flag).

Links in the readme#Configuration_variables didn't seem right, as it's too verbose.  Perhaps a dedicated section?

Between the readme or the comments, it should also spell out whether leaving both false is permissible.

**Comment by ericgomes56** [comment]
Active-Active = 'activeactive' in Helm Chart, and Active-Passive = 'clustermode'.  If you are interested in using either mode, one needs to be enabled true, while the other is false.  You can't have both environment variable values set to true at the same time.  Both environment variables values can be set to false too as this is not a mandatory requirement to deploy Aqua.

As you mentioned, the Active-Passive will be deprecated and has a disadvantage versus Active-Active setup.  In Active-Passive, there is a failover process which can take a few minutes for the other aqua-web to reinitialize itself.  When using Active-Active, there is no failover process and there isn't any downtime if one aqua-web pod malfunctions.

**Comment by agilgur5** [comment]
Thanks folks, I've made a small PR (#113) to modify the docs to clarify what is what and which is which per your comments

**Comment by KoppulaRajender** [comment]
updated Readme, thanks

**Comment by agilgur5** [comment]
It looks like #272 #273 #274 word-for-word copied my much earlier PR for docs changes in #113 ... except they didn't add the comment in the `values` that I did.

Not really kosher to do so without crediting the original author (e.g. list them as author and you as _committer_)...
